### ISSUE TITLE
Feature: use external programs to process data

### ISSUE THREAD

**Issue by xantorohara** [xantorohara/rocket-table#2]
Call other applications to read, process, write tabular data

**Comment by xantorohara** [comment]
Implemented

**Comment by zzzzqqqa** [comment]
It reports programs.json missing error when programs.json is not in the same folder of the dataset.

**Comment by xantorohara** [comment]
Will check and fix this. Thanks

**Comment by xantorohara** [comment]
> It reports programs.json missing error when programs.json is not in the same folder of the dataset.

Thanks!
Fixed in scope of #5 
Please, checkout rocket-table-1.1.2.zip

**Comment by zzzzqqqa** [comment]
> > It reports programs.json missing error when programs.json is not in the same folder of the dataset.
> 
> Thanks!
> Fixed in scope of #5
> Please, checkout rocket-table-1.1.2.zip

It works well now. The new function is very helpful and also very flexible. Thank you.
